# Generated by Django 5.2 on 2025-05-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_blacklistedtoken_consultationtype_passwordresetcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='startups',
            field=models.ManyToManyField(blank=True, related_name='personne_memberships', to='account.startup'),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='profile_memberships', to='account.personne'),
        ),
    ]
