# Generated by Django 5.2 on 2025-05-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_personne_startups_alter_startupprofile_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='personneprofile',
            name='startups',
            field=models.ManyToManyField(related_name='memberss', to='account.startup'),
        ),
    ]
