# Generated by Django 5.2 on 2025-05-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_personneprofile_startups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='consultation_type',
            field=models.CharField(choices=[('Financial', 'Financial'), ('Strategic', 'Strategic'), ('It', 'It')], default='Strategic', max_length=30),
        ),
        migrations.DeleteModel(
            name='ConsultationType',
        ),
    ]
