# Generated by Django 5.2 on 2025-05-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_consultationrequest_consultation_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupSignupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nom_leader', models.CharField(max_length=255)),
                ('genre_leader', models.CharField(max_length=50)),
                ('date_naissance_leader', models.DateField()),
                ('adresse', models.TextField()),
                ('numero_telephone', models.CharField(max_length=10)),
                ('wilaya', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateField()),
                ('secteur', models.CharField(max_length=50)),
                ('document', models.FileField(upload_to='startup_documents/')),
                ('is_processed', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
