# Generated by Django 5.2 on 2025-05-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_startupsignuprequest_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupsignuprequest',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupsignuprequest',
            name='date_creation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupsignuprequest',
            name='date_naissance_leader',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupsignuprequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupsignuprequest',
            name='genre_leader',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startupsignuprequest',
            name='nom_leader',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='startupsignuprequest',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='startupsignuprequest',
            name='secteur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startupsignuprequest',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='date_creation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='date_naissance_leader',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='nom_leader',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='secteur',
            field=models.CharField(blank=True, choices=[('Tech', 'Technologie'), ('Health', 'Santé'), ('Finance', 'Finance')], max_length=50, null=True, verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='startup',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wilaya'),
        ),
    ]
