# Generated by Django 5.2 on 2025-05-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_startupsignuprequest_adresse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='startup_documents/'),
        ),
    ]
