# Generated by Django 5.2 on 2025-05-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_startup_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='genre_leader',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=50, null=True),
        ),
    ]
